{% set version = "2.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-colorramps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/colorRamps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/colorRamps/colorRamps_{{ version }}.tar.gz
  sha256: 61f1290824380ae2fe4649f296649e0a155b73ced41479686150400f8a9c568a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('colorRamps')"           # [not win]
    - "\"%R%\" -e \"library('colorRamps')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=colorRamps
  license: GPL-2.0-or-later
  summary: Builds gradient color maps
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
