travis:
  secure:
    BINSTAR_TOKEN: eCjmdHT13oLvkFKBz2UbzUz5utO3fTQR0nLVUvirAoW+E+cJbrmjZyaCirlLyOgrPYOUjMuB56WEhAv7e0Ajx7PiTTM5dUHXLQloBlLJ2gdb9ZZUUVlEVU8fb79RYcBrSosEfUHD5nWmCTFfqi2kiZOJRfk0EE5Tja+AeAiyWZNUW4MowskiDW2V6f9lU71wJ/0zCUdO+pK+alWB1KRfuX6lEJAGWQXJ/uLqSa9SNN7mB74OOqmc+JYJvhY/TxIL4SsCRLXn38TsQxkGSjURZHUmYAqg0Zeig1kSjx3yDEaitbvzaiXJ38AfrUSuCOUQBzcU+ol0dCIlBK8Gg4ztFQVrxURzdMFWo7RdmIPwXWRGa3yJAzCZdsDvLpSiLqhJtzN2xMu6tITn8eWZ6ls5FuABpYcNW4lf7YiD71sV7D/T7zMzxQq+HSTJAzVaDzI32mjrjIZmLpcQOdVNCAXAdJ/SQsrLCof+wTzRfmhn+SB9mirogF/q6EpfqpqUVPljsnLZkknL1HxTPzKNFEXSEBwhN3YIl5kVcC55ncxydOU7EyWjUcF6bIHCnKz9ns3lA+BrwnjWegM6dyeG2fVpOzf7+0IfM7Sm08QZgDFSt71aaBOqhSwauZKI+DdCqhfxIjIUb0immvCofCZxj6eKZjjqycbZh+NryrA9D28ECZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
