appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KZrU6VwgbXaKWmS0tDAcCmwJSV8tqiGwk5M0C/3T4KX1bC4GVr5no+P8wy/8y1YKAvLkoN071eInxhlirOFy1hob+t5eMSPgCYxchf+mYRN1ySjRX7I21gYxysMJ3sppNSSscGOHkB3z+qhJQNVKMb/p/s3uVMBT1MjcYUUElx/FVYcPhk9cXOD2PLWSzm7G65xFKLknDhHAo4BBlrbewLTsqCbhTNN9JL3Zp1GsXFFQP+4pxZnS1mx+S1b7BULcGO6LSVBb+WomiDRbVSZmDMkAntUuMaH+oOpHE5Y6cMm7ODrTmS0GdNGOHS9qtOJqTpyJNU0MMH5xymz72R2uKidK0sR98D9IZJhMhUgqW28miqH9eMEKZgBzqTTJ+YRQONc/74LUdko6tb9vIM7hLL17twFP89gUmt8qBGbszpIuZylFknpDnw2lkd/DIXzCPPE9PB6qFd6kJlJjUvWm1785Xy4RIdcon5rbrEw7s5k7ARtgboBPa/Rs+nmf4fprHL/XW8yViqUW02eQVQh/nyobdosm4F2BJIGuMI8R3CLXrVVeO7daLvKvE9JRed3tI3aVEre/RVr2YCUcnJ0uq+ma5oSdmbv6LyAJ7bvczkD7GLpoEglr3MrO/RuI89EBePc8plYZcIFTtrqp4nELvnqHloHqr68pPd66CiC56aE=}
